# Site settings
title: Nelli Holopainen UXE
email: nelli.holopainen@gmail.com
url: https://github.com/nellihol
description: "Nelli Holopainen - User Experience Engineer. Current UX/HCI Master's degree student with a background in Front End Development.  I aim to be the missing link between the business, user and technology needs, using user research, rapid prototyping and modern web technologies to transform complex problems and pain points into elegant digital solutions."
keywords: "User experience, UX, UI, Design Thinking, Web Development, Front End development, Personas, Agile, Scrum, Interaction design, Graphic design"
skills: "User experience engineer"
meta_author: Nelli Holopainen

# Google webmaster tools
google_verify: gJ4fEcVbztA1gxpaiPOQWi9ekJDcY6vcd3-PWkXL240

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f8c3d6 #80B3FF
  secondary: 121640 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nelli Holopainen
  location: Australia
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/nellihol
  - title: twitter
    url: http://twitter.com/nellihol
  - title: linkedin
    url: https://www.linkedin.com/in/nelliholopainen/

# Postal address (add as many lines as necessary)
address:


# Credits content
credits: 'yahoo'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
